management:
  server:
    port: ${APPL_MANAGEMENT_SERVER_PORT:8090}
server:
  port: ${APPL_SERVER_PORT:8080}
  redis:
    host: ${APPL_REDIS_HOST:localhost}
    password: ${APPL_REDIS_PASSWORD}
    port: ${APPL_REDIS_PORT:6379}
  session:
    store-type: redis
